[package]
name = "wpilib-native-utils"
edition = "2024"
version = "1.0.0"
license.workspace = true
authors.workspace = true
homepage.workspace = true
repository.workspace = true
keywords.workspace = true
categories = ["development-tools::build-utils", "science::robotics"]
description = "Build-script library to locate/download/compile against WPILib build environments"

[dependencies]
anyhow.workspace = true
ureq.workspace = true
which.workspace = true
zip.workspace = true