[package]
name = "wpiutil"
edition = "2024"
description = "Rust bindings for WPIUtil"
version.workspace = true
license.workspace = true
authors.workspace = true
repository.workspace = true

[features]

[dependencies]
wpiutil-sys = { path = "../wpiutil-sys"}