#include "hal/AddressableLED.h"
#include "hal/AddressableLEDTypes.h"
#include "hal/AnalogInput.h"
#include "hal/CAN.h"
#include "hal/CANAPI.h"
#include "hal/CANAPITypes.h"

#include "hal/CTREPCM.h"
#include "hal/Constants.h"
#include "hal/Counter.h"
#include "hal/DIO.h"
#include "hal/DriverStation.h"
#include "hal/DriverStationTypes.h"
#include "hal/DutyCycle.h"
#include "hal/Encoder.h"
#include "hal/Errors.h"
#include "hal/Extensions.h"
#include "hal/HALBase.h"
#include "hal/I2C.h"
#include "hal/I2CTypes.h"
#include "hal/IMU.h"
#include "hal/IMUTypes.h"
#include "hal/Main.h"
#include "hal/Notifier.h"
#include "hal/Ports.h"
#include "hal/Power.h"
#include "hal/PowerDistribution.h"
#include "hal/REVPH.h"
#include "hal/SerialPort.h"
#include "hal/SimDevice.h"

// this SERIOUSLY needs ntcore. I will deal with this later.
// #include "hal/SystemServer.h"
#include "hal/Threads.h"
#include "hal/Types.h"
#include "hal/UsageReporting.h"
#include "hal/Value.h"

// Some classes use WPI_String, so we include this.
// The proper wpihal library will wrap this in safe abstractions that automatically Drop
#include "wpi/string.h"

// simulation
#include "hal/simulation/AddressableLEDData.h"
#include "hal/simulation/AnalogInData.h"
#include "hal/simulation/CTREPCMData.h"
#include "hal/simulation/CanData.h"
#include "hal/simulation/DIOData.h"
#include "hal/simulation/DigitalPWMData.h"
#include "hal/simulation/DriverStationData.h"
#include "hal/simulation/DutyCycleData.h"
#include "hal/simulation/EncoderData.h"
#include "hal/simulation/I2CData.h"
#include "hal/simulation/MockHooks.h"
#include "hal/simulation/NotifierData.h"
#include "hal/simulation/NotifyListener.h"
#include "hal/simulation/PWMData.h"
#include "hal/simulation/PowerDistributionData.h"
#include "hal/simulation/REVPHData.h"
#include "hal/simulation/Reset.h"
#include "hal/simulation/RoboRioData.h"
//#include "hal/simulation/SimCallbackRegistry.h"
//#include "hal/simulation/SimDataValue.h"
#include "hal/simulation/SimDeviceData.h"