[target.arm-unknown-linux-gnueabi]
linker = "arm-frc2025-linux-gnueabi-gcc"
ar = "arm-frc2025-linux-gnueabi-ar"
rustflags = [
  "-C", "target-cpu=cortex-a9"
]
[target.aarch64-unknown-linux-gnu]
linker = "aarch64-bookworm-linux-gnu-gcc"
ar = "aarch64-bookworm-linux-gnu-ar"