[package]
name = "wpilib-nativeutils"
edition = "2021"
version.workspace = true
license.workspace = true
authors.workspace = true
repository.workspace = true
description = "Utility to pull down Maven artifacts from the WPILib Artifactory"

[dependencies]
anyhow = "1.0.93"
home = "0.5.9"
reqwest = { version = "0.12.9", default-features = false, features = ["blocking", "rustls-tls"] }
zip = "4.3.0"
which = "8.0.0"