[package]
name = "wpilib-nativeutils"
edition = "2024"
version.workspace = true
license.workspace = true
authors.workspace = true
repository.workspace = true
description = "Utility to pull down Maven artifacts from the WPILib Artifactory"

[dependencies]
anyhow.workspace = true
home.workspace = true
reqwest.workspace = true
which.workspace = true
zip.workspace = true