[package]
name = "wpilib-nativeutils-tester"
version.workspace = true
license.workspace = true
authors.workspace = true
repository.workspace = true
edition = "2021"

[dependencies]
wpilib-nativeutils = { path = "../wpilib-nativeutils" }