name: CI

#on: [workflow_dispatch]
on: [push, pull_request, workflow_dispatch]

jobs:
  build-docker:
    strategy:
      fail-fast: false
      matrix:
        include:
          - container: wpilib/systemcore-cross-debian:trixie
            artifact-name: SystemCore
            target: "aarch64-unknown-linux-gnu"
            flags: "--features robot-controller"
            aarch64-linker: "aarch64-systemcore2027-linux-gnu"
          - container: wpilib/aarch64-cross-debian:trixie
            artifact-name: Arm64
            target: "aarch64-unknown-linux-gnu"
            flags: ""
            aarch64-linker: "aarch64-trixie-linux-gnu"
          - container: wpilib/systemcore-cross-debian:trixie
            artifact-name: Linux
            target: "x86_64-unknown-linux-gnu"
            flags: ""
    name: "Build - ${{ matrix.artifact-name }}"
    runs-on: ubuntu-26.04
    container: ${{ matrix.container }}
    steps:
      - name: Install build dependencies
        run: apt-get update && apt-get install -y libclang-dev
      - uses: actions/checkout@v6
        with:
          submodules: true
          fetch-depth: 0
      - name: Fetch all history and metadata
        run: |
          git config --global --add safe.directory /__w/${{ github.event.repository.name }}/${{ github.event.repository.name }}
      - name: Install rust target toolchain
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          target: ${{ matrix.target }}
      - name: Configure aarch64 linkage
        if: ${{ matrix.aarch64-linker != '' }}
        run: |
          echo "CARGO_TARGET_AARCH64_UNKNOWN_LINUX_GNU_LINKER=${{ matrix.aarch64-linker }}-gcc" >> $GITHUB_ENV
          echo "CARGO_TARGET_AARCH64_UNKNOWN_LINUX_GNU_AR=${{ matrix.aarch64-linker }}-ar" >> $GITHUB_ENV

      - name: Attempt to build library
        run: cargo build --target=${{ matrix.target }} -p build-test ${{ matrix.flags }}
      - name: Attempt to run the build-test
        run: cargo run -p build-test ${{ matrix.flags }} && cargo run -p build-test ${{ matrix.flags }} --release

  build-host:
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: windows-latest
            artifact-name: WinX64
            architecture: x64
            flags: ""
          - os: windows-latest
            artifact-name: WinArm64
            architecture: aarch64
            flags: ""
          - os: macos-26
            artifact-name: macOS
            architecture: aarch64
            flags: ""
    name: "Build - ${{ matrix.artifact-name }}"
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v6
        with:
          submodules: true
          fetch-depth: 0
      - uses: actions-rust-lang/setup-rust-toolchain@v1
      - name: Attempt to build/run library
        run: cargo run -p build-test ${{ matrix.flags }} && cargo run -p build-test ${{ matrix.flags }} --release
